version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 10
  labels:
  - kind/dependency
  - do-not-merge/work-in-progress
  ignore:
  - dependency-name: Microsoft.VisualStudio.Telemetry
    versions:
    - "> 16.3.2"
  - dependency-name: Com.Airbnb.Android.Lottie
    versions:
    - "> 3.0.4, < 3.1"
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - ">= 2.2.a, < 2.3"
  - dependency-name: CommonServiceLocator
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: NUnit.Runners
    versions:
    - ">= 3.10.a, < 3.11"
  - dependency-name: Microsoft.CodeAnalysis.VisualBasic
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: Microsoft.NETCore.UniversalWindowsPlatform
    versions:
    - "> 6.1.9"
  - dependency-name: microsoft.visualstudio.texttemplating.15.0
    versions:
    - "> 16.3.29316.127"
  - dependency-name: Xamarin.AndroidX.Fragment
    versions:
    - ">= 1.2.a, < 1.3"
  - dependency-name: Microsoft.Extensions.Logging.Debug
    versions:
    - ">= 2.2.a, < 2.3"
  - dependency-name: Microsoft.AppCenter
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: Microsoft.CodeAnalysis.CSharp.Workspaces
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: Refit
    versions:
    - ">= 4.7.a, < 4.8"
  - dependency-name: Microsoft.TypeScript.MSBuild
    versions:
    - ">= 3.5.a, < 3.6"
  - dependency-name: Moq
    versions:
    - ">= 4.11.a, < 4.12"
  - dependency-name: Mono.Cecil
    versions:
    - ">= 0.11.a, < 0.12"
  - dependency-name: docfx.console
    versions:
    - ">= 2.45.a, < 2.46"
  - dependency-name: GitVersionTask
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: cef.redist.x64
    versions:
    - "> 3.3396.1786"
  - dependency-name: CommonServiceLocator
    versions:
    - "> 1.3"
  - dependency-name: System.Reactive
    versions:
    - "> 4.1.0, < 4.2"
  - dependency-name: Microsoft.Extensions.Logging.Debug
    versions:
    - "> 1.1.1"
  - dependency-name: CefSharp.Wpf
    versions:
    - "> 67.0.0"
  - dependency-name: cef.redist.x86
    versions:
    - "> 3.3396.1786"
  - dependency-name: Microsoft.CodeAnalysis.VisualBasic
    versions:
    - ">= 3.0.a, < 3.1"
  - dependency-name: Microsoft.Build.Engine
    versions:
    - "> 15.4.8"
  - dependency-name: Microsoft.Build.Framework
    versions:
    - "> 15.8.166"
  - dependency-name: CefSharp.Common
    versions:
    - "> 67.0.0"
  - dependency-name: Microsoft.CodeAnalysis.CSharp.Workspaces
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: Microsoft.CodeAnalysis.Workspaces.MSBuild
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: Microsoft.CodeAnalysis
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: Microsoft.CodeAnalysis.Workspaces.Common
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: CefSharp.Common
    versions:
    - ">= 73.a, < 74"
  - dependency-name: Mono.Cecil
    versions:
    - "> 0.9.5.4, < 0.10"
  - dependency-name: BenchmarkDotNet
    versions:
    - ">= 0.12.a, < 0.13"
  - dependency-name: GtkSharp
    versions:
    - "> 3.24.24.4, < 3.25"
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - ">= 2.14.a, < 2.15"
  - dependency-name: Uno.Wasm.Bootstrap.DevServer
    versions:
    - "> 1.3.4, < 1.4"
  - dependency-name: Uno.Wasm.Bootstrap
    versions:
    - "> 1.3.4, < 1.4"
  - dependency-name: Xamarin.GooglePlayServices.Location
    versions:
    - ">= 117.1.a, < 117.2"
  - dependency-name: Microsoft.VisualStudio.ComponentModelHost
    versions:
    - "> 15.8.525"
  - dependency-name: Microsoft.UI.Xaml
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: System.Memory
    versions:
    - "> 4.5.2"
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - ">= 3.0.a, < 3.1"
  - dependency-name: Com.Airbnb.Android.Lottie
    versions:
    - ">= 3.4.a, < 3.5"
  - dependency-name: Microsoft.Build.Utilities.Core
    versions:
    - ">= 16.a, < 17"
  - dependency-name: Microsoft.Build.Framework
    versions:
    - "> 15.4.8"
  - dependency-name: Microsoft.CodeAnalysis.Common
    versions:
    - ">= 3.6.a, < 3.7"
  - dependency-name: Microsoft.CodeAnalysis.Workspaces.Common
    versions:
    - ">= 3.6.a, < 3.7"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.11.0
    versions:
    - "> 11.0.61031"
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - ">= 3.6.a, < 3.7"
  - dependency-name: Microsoft.CodeAnalysis.VisualBasic
    versions:
    - "> 3.6.0"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.15.3.DesignTime
    versions:
    - "> 15.0.26929"
  - dependency-name: Microsoft.VisualStudio.Shell.15.0
    versions:
    - "> 15.9.28307"
  - dependency-name: Microsoft.CodeAnalysis
    versions:
    - "> 3.3.1"
  - dependency-name: Microsoft.VisualStudio.Imaging
    versions:
    - "> 15.9.28307"
  - dependency-name: Microsoft.TypeScript.MSBuild
    versions:
    - "> 3.9.2, < 3.10"
  - dependency-name: Microsoft.VisualStudio.Utilities
    versions:
    - "> 15.9.28307"
  - dependency-name: Microsoft.Identity.Client
    versions:
    - "> 4.15.0"
  - dependency-name: Microsoft.VisualStudio.SDK.EmbedInteropTypes
    versions:
    - "> 15.0.16"
  - dependency-name: Microsoft.Graph
    versions:
    - ">= 3.9.a, < 3.10"
  - dependency-name: Microsoft.CodeAnalysis.CSharp.Workspaces
    versions:
    - "> 3.3.1"
  - dependency-name: EnvDTE100
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.12.0
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Microsoft.VisualStudio.TextManager.Interop.8.0
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.14.0.DesignTime
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.8.0
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Microsoft.VisualStudio.OLE.Interop
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Microsoft.CodeAnalysis.Workspaces.MSBuild
    versions:
    - ">= 3.3.a, < 3.4"
  - dependency-name: Microsoft.Build.Utilities.Core
    versions:
    - "> 15.4.8"
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - "> 2.12.0, < 2.13"
  - dependency-name: ManagedEsent
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: NuGet.VisualStudio
    versions:
    - ">= 4.6.a, < 4.7"
  - dependency-name: Microsoft.VisualStudio.ImageCatalog
    versions:
    - "> 15.9.28307"
  - dependency-name: Microsoft.VisualStudio.Threading.Analyzers
    versions:
    - "> 15.8.209"
  - dependency-name: NUnit3TestAdapter
    versions:
    - "> 3.16.0, < 3.17"
  - dependency-name: Microsoft.VisualStudio.Text.Data
    versions:
    - "> 15.6.27740"
  - dependency-name: Microsoft.VisualStudio.Shell.Framework
    versions:
    - "> 15.9.28307"
  - dependency-name: Microsoft.VisualStudio.Threading
    versions:
    - "> 15.8.209"
  - dependency-name: System.Management
    versions:
    - ">= 4.7.a, < 4.8"
  - dependency-name: microsoft.visualstudio.texttemplating.15.0
    versions:
    - ">= 16.4.a, < 16.5"
  - dependency-name: Microsoft.TypeScript.MSBuild
    versions:
    - ">= 3.7.a, < 3.8"
  - dependency-name: Microsoft.VisualStudio.CoreUtility
    versions:
    - "> 15.6.27740"
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: microsoft.visualstudio.texttemplating.15.0
    versions:
    - ">= 16.5.a, < 16.6"
  - dependency-name: Microsoft.CodeAnalysis.CSharp.Workspaces
    versions:
    - ">= 3.5.a, < 3.6"
  - dependency-name: Microsoft.AppCenter
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: Microsoft.Build
    versions:
    - "> 15.4.8"
  - dependency-name: StreamJsonRpc
    versions:
    - "> 2.2.34, < 2.3"
  - dependency-name: Microsoft.CodeAnalysis.CSharp.Workspaces
    versions:
    - ">= 3.4.a, < 3.5"
  - dependency-name: Microsoft.Build.Utilities.Core
    versions:
    - ">= 16.4.a, < 16.5"
  - dependency-name: Microsoft.Graph
    versions:
    - ">= 3.14.a, < 3.15"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.15.6.DesignTime
    versions:
    - ">= 16.7.a, < 16.8"
  - dependency-name: Moq
    versions:
    - "> 4.14.6, < 4.15"
  - dependency-name: Microsoft.Build.Tasks.Core
    versions:
    - "> 15.4.8"
  - dependency-name: Xamarin.Android.Support.v7.RecyclerView
    versions:
    - "> 28.0.0.1"
  - dependency-name: Xamarin.AndroidX.Lifecycle.LiveData
    versions:
    - "> 2.2.0.2"
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - ">= 2.13.a, < 2.14"
  - dependency-name: Microsoft.TypeScript.MSBuild
    versions:
    - ">= 3.8.a, < 3.9"
  - dependency-name: Microsoft.CodeAnalysis.Workspaces.Common
    versions:
    - "> 3.3.1"
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - "> 3.3.1"
  - dependency-name: Microsoft.CodeAnalysis.Common
    versions:
    - "> 3.3.1"
  - dependency-name: Xamarin.AndroidX.Browser
    versions:
    - "> 1.0.0, < 1.1"
  - dependency-name: Xamarin.AndroidX.Browser
    versions:
    - ">= 1.2.a, < 1.3"
  - dependency-name: Com.Airbnb.Android.Lottie
    versions:
    - ">= 3.5.a, < 3.6"
  - dependency-name: Microsoft.Graph
    versions:
    - "> 3.12.0, < 4"
  - dependency-name: Xamarin.AndroidX.Lifecycle.LiveData
    versions:
    - "> 2.2.0.2, < 2.3"
  - dependency-name: Microsoft.Graph
    versions:
    - ">= 3.15.a, < 3.16"
  - dependency-name: Xamarin.AndroidX.AppCompat.AppCompatResources
    versions:
    - "> 1.1.0.1, < 1.2"
  - dependency-name: Microsoft.Identity.Client
    versions:
    - ">= 4.16.a, < 4.17"
  - dependency-name: Uno.SourceGenerationTasks
    versions:
    - "> 2.0.6, < 2.1"
  - dependency-name: Com.Airbnb.iOS.Lottie
    versions:
    - "> 2.5.11, < 2.6"
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - ">= 2.15.a, < 2.16"
  - dependency-name: Microsoft.TeamFoundationServer.Client
    versions:
    - ">= 16.170.a, < 16.171"
  - dependency-name: Microsoft.VisualStudio.Services.InteractiveClient
    versions:
    - ">= 16.170.a, < 16.171"
  - dependency-name: SkiaSharp.NativeAssets.Linux
    versions:
    - "> 2.80.0, < 2.81"
  - dependency-name: SkiaSharp
    versions:
    - "> 2.80.0, < 2.81"
  - dependency-name: Jellyfin.SkiaSharp.NativeAssets.LinuxArm
    versions:
    - "> 1.68.0, < 1.69"
  - dependency-name: Microsoft.AppCenter
    versions:
    - ">= 3.4.a, < 3.5"
  - dependency-name: stdole
    versions:
    - "> 7.0.3303"
  - dependency-name: Microsoft.CodeAnalysis.VisualBasic.Workspaces
    versions:
    - "> 3.6.0"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.10.0
    versions:
    - "> 10.0.30320"
  - dependency-name: Microsoft.VisualStudio.TextManager.Interop
    versions:
    - "> 7.10.6071"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.9.0
    versions:
    - "> 9.0.30730"
  - dependency-name: Microsoft.CodeAnalysis.Workspaces.MSBuild
    versions:
    - "> 3.6.0"
  - dependency-name: Microsoft.Identity.Client
    versions:
    - ">= 4.17.a, < 4.18"
  - dependency-name: SkiaSharp.Views
    versions:
    - "> 1.68.0, < 1.69"
  - dependency-name: Microsoft.VisualStudio.OLE.Interop
    versions:
    - "> 7.10.6071, < 7.11"
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: Uno.Wasm.Bootstrap
    versions:
    - "> 2.0.0.pre.dev.180, < 2.1"
  - dependency-name: Microsoft.VisualStudio.Validation
    versions:
    - "> 16.8.33"
  - dependency-name: Microsoft.Win32.Registry
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: Xamarin.AndroidX.Fragment
    versions:
    - "> 1.3.0.1"
  - dependency-name: Com.Airbnb.Android.Lottie
    versions:
    - "> 3.0.4"
  - dependency-name: System.ComponentModel.Composition
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: Uno.Wasm.Bootstrap.DevServer
    versions:
    - "> 2.0.0.pre.dev.180, < 2.1"
  - dependency-name: System.Reflection.Emit
    versions:
    - ">= 4.7.a, < 4.8"
  - dependency-name: Newtonsoft.Json
    versions:
    - ">= 13.0.a, < 13.1"
  - dependency-name: Uno.Core
    versions:
    - ">= 2.1.a, < 2.2"
  - dependency-name: Xamarin.AndroidX.Browser
    versions:
    - ">= 1.3.a, < 1.4"
  - dependency-name: NUnit.Engine
    versions:
    - ">= 3.12.a, < 3.13"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.15.6.DesignTime
    versions:
    - ">= 16.9.a, < 16.10"
  - dependency-name: Moq
    versions:
    - "> 4.16.0, < 4.17"
  - dependency-name: StreamJsonRpc
    versions:
    - ">= 2.7.a, < 2.8"
  - dependency-name: MSTest.TestFramework
    versions:
    - ">= 2.2.a, < 2.3"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.12.0
    versions:
    - ">= 16.9.a, < 16.10"
  - dependency-name: Microsoft.VisualStudio.OLE.Interop
    versions:
    - ">= 16.9.a, < 16.10"
  - dependency-name: Xamarin.GooglePlayServices.Location
    versions:
    - "> 117.0.0"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.14.0.DesignTime
    versions:
    - ">= 16.9.a, < 16.10"
  - dependency-name: Xamarin.AndroidX.Legacy.Support.v4
    versions:
    - "> 1.0.0, < 1.1"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop.8.0
    versions:
    - "> 8.0.50728"
  - dependency-name: Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime
    versions:
    - "> 14.3.26931"
  - dependency-name: EnvDTE100
    versions:
    - "> 10.0.3"
  - dependency-name: NuGet.VisualStudio
    versions:
    - "> 4.5.0"
  - dependency-name: Microsoft.VisualStudio.Shell.Interop
    versions:
    - "> 7.10.6073"
  - dependency-name: Microsoft.VisualStudio.TextManager.Interop.8.0
    versions:
    - "> 8.0.50728"
  - dependency-name: Microsoft.ProjectReunion.WinUI
    versions:
    - 0.5.5
  - dependency-name: Xamarin.UITest
    versions:
    - 3.0.16
  - dependency-name: Microsoft.Toolkit.Uwp.UI.Lottie
    versions:
    - 7.0.1
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.2.1
  - dependency-name: Microsoft.TypeScript.MSBuild
    versions:
    - 4.2.2
  - dependency-name: Xamarin.AndroidX.Fragment
    versions:
    - 1.3.0
  commit-message:
    prefix: chore
    include: scope
