name: Check Links

on:
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest
    name: Check Docs links
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Import External Doc
        run: pwsh ./doc/import_external_docs.ps1
        
      - name: Move external inside Doc dir
        run : mv ./articles/external ./doc/articles/
        
      - name: Move Hot Design doc inside Doc dir
        run: mv "./articles/studio/Hot Design" ./doc/articles/
      
      - name: Check links
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --verbose
            --no-progress
            --accept 200..=204,429
            ./doc/**/*.md
            
