name: Update UWP Generated Branch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UnoCheck_Version: '1.17.0'
  UnoCheck_Manifest: 'https://raw.githubusercontent.com/unoplatform/uno.check/4befa714987c2581e205cec9a56d48b32d76c843/manifests/uno.ui.manifest.json'

  # Only convert using NetPrevious
  UnoDisableNetCurrentMobile: true
  UnoDisableNetCurrent: true

jobs:
  build:
    name: update-uwp-branch
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Pin .NET Version
      run: |
        (Get-Content global.json).replace("latestFeature", "disable") | Set-Content global.json

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.10.3'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        useConfigFile: true
        configFilePath: gitversion.yml

    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - run: |
       echo "JAVA_HOME=$env:JAVA_HOME_11_X64" >> $env:GITHUB_ENV
       echo "JavaSdkDirectory=$env:JAVA_HOME_11_X64" >> $env:GITHUB_ENV
      name: Select JDK 11

    - run: |
        & dotnet tool update --global uno.check --version $env:UnoCheck_Version --add-source https://api.nuget.org/v3/index.json
        & uno-check -v --ci --non-interactive --fix --skip androidsdk --skip androidemulator --skip xcode --skip gtk3 --skip vswin --skip vsmac --manifest $env:UnoCheck_Manifest
      name: Install .NET Workloads

    - name: Run API Sync Tool
      run: |
        cd $env:GITHUB_WORKSPACE\build
        msbuild Uno.UI.Build.csproj /v:m "/p:CombinedConfiguration=Release|AnyCPU" /m /t:RunAPISyncTool /bl

    - name: Commit to repository
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        Set-PSDebug -Trace 1
        git add .
        git commit -m "Update UWP Autoconvert from $env:GITHUB_SHA"
        git push origin $env:GITHUB_REF_NAME`:generated/$env:GITHUB_REF_NAME/uwp-autoconvert -f
